name: 02 - Workflow Events

on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "event name is:" ${{ github.event_name }}
